name: bitirme
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_onboarding_slider: ^1.0.11
  provider: ^6.1.2
  simple_animation_progress_bar: ^1.8.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/daibet_logo.jpg"


flutter:

  uses-material-design: true

  assets:
    - images/
    
